configure:
  - -Db_coverage=true
  - -Dgenerate_parsers=false
  - -Dlibrope:test=false
  - -Dlibhighlight:test=false
  - -Dliblsp:test=false
  - -Dlibttyui:test=false
  - -Dlibeditorconfig:test=false
  - -Db_sanitize=address,undefined
  - -Dwerror=true
env:
  CC_LD: mold
default:
  - test
