configure:
  - -Db_coverage=true
  - -Dgenerate_parsers=false
  - -Dlibrope:test=true
  - -Dlibhighlight:test=true
  - -Dliblsp:test=true
  - -Dlibttyui:test=true
  - -Dlibeditorconfig:test=true
env:
  CC_LD: mold
default:
  - test
