#include <highlight.h>

#define HIGHLIGHT_POSITION_POOL_SIZE 32

#define LENGTH(x) (sizeof(x) / sizeof(x[0]))
#define STATIC_ASSERT(c) _Static_assert(c, #c)
#define HIGHLIGHT_NO_CAPTURE UINT32_MAX
#define HIGHLIGHT_DIVIDE_CEIL(x, y) ((x) / (y) + !!((x) % (y)))
#define HIGHLIGHT_SPECIAL_MASK (~(UINT32_MAX >> 1))
#define HIGHLIGHT_IS_SPECIAL(x) ((x) & HIGHLIGHT_SPECIAL_MASK)
#define HIGHLIGHT_CAPTURE_ID(x) ((x) & ~HIGHLIGHT_SPECIAL_MASK)

enum HighlightSpecialCaptures {
	HIGHLIGHT_SPECIAL_INJECTION_CONTENT,
	HIGHLIGHT_SPECIAL_INJECTION_LANGUAGE,
	HIGHLIGHT_SPECIAL_LOCAL_DEF,
	HIGHLIGHT_SPECIAL_LOCAL_DEF_VALUE,
	HIGHLIGHT_SPECIAL_LOCAL_REF,
	HIGHLIGHT_SPECIAL_LOCAL_SCOPE,
	HIGHLIGHT_SPECIAL_END,
};
